"""
Module for generating embeddings for RAG system.
"""

import os
from typing import List, Union
import numpy as np
from sentence_transformers import SentenceTransformer
import cohere
from dotenv import load_dotenv


class EmbeddingGenerator:
    """
    A class to generate embeddings using different models (Cohere, Sentence Transformers, etc.)
    """
    
    def __init__(self, model_name: str = "all-MiniLM-L6-v2", api_key: str = None):
        """
        Initialize the embedding generator.
        
        Args:
            model_name: Name of the model to use for embeddings
            api_key: API key for services like Cohere
        """
        load_dotenv()
        
        # Use either Cohere or SentenceTransformers based on availability and preference
        self.model_name = model_name
        self.use_cohere = api_key is not None or os.getenv("COHERE_API_KEY") is not None
        
        if self.use_cohere:
            cohere_api_key = api_key or os.getenv("COHERE_API_KEY")
            if not cohere_api_key:
                raise ValueError("Cohere API key is required when using Cohere embeddings")
            self.client = cohere.Client(cohere_api_key)
            print("Using Cohere embeddings")
        else:
            print(f"Using SentenceTransformer model: {model_name}")
            self.model = SentenceTransformer(model_name)
    
    def generate_embedding(self, text: str) -> List[float]:
        """
        Generate embedding for a single text.
        
        Args:
            text: Input text
            
        Returns:
            Embedding vector as a list of floats
        """
        if self.use_cohere:
            response = self.client.embed(
                texts=[text],
                model="embed-multilingual-v2.0",  # Using multilingual model
                truncate="END"
            )
            return response.embeddings[0]
        else:
            embedding = self.model.encode([text])[0]
            return embedding.tolist()
    
    def generate_embeddings(self, texts: List[str]) -> List[List[float]]:
        """
        Generate embeddings for a list of texts.
        
        Args:
            texts: List of input texts
            
        Returns:
            List of embedding vectors
        """
        if self.use_cohere:
            response = self.client.embed(
                texts=texts,
                model="embed-multilingual-v2.0",
                truncate="END"
            )
            return [embedding for embedding in response.embeddings]
        else:
            embeddings = self.model.encode(texts)
            return [embedding.tolist() for embedding in embeddings]
    
    def get_embedding_dimension(self) -> int:
        """
        Get the dimension of the embeddings generated by this model.
        
        Returns:
            Dimension of the embeddings
        """
        # Generate a test embedding to determine dimension
        test_embedding = self.generate_embedding("Test text")
        return len(test_embedding)


class CohereEmbeddingGenerator:
    """
    Specialized class for generating embeddings using Cohere API.
    """
    
    def __init__(self, api_key: str = None):
        """
        Initialize with Cohere client.
        
        Args:
            api_key: Cohere API key
        """
        load_dotenv()
        self.api_key = api_key or os.getenv("COHERE_API_KEY")
        if not self.api_key:
            raise ValueError("Cohere API key is required")
        
        self.client = cohere.Client(self.api_key)
        self.model_name = "embed-multilingual-v2.0"
    
    def generate_embedding(self, text: str) -> List[float]:
        """
        Generate embedding for a single text.
        
        Args:
            text: Input text
            
        Returns:
            Embedding vector as a list of floats
        """
        response = self.client.embed(
            texts=[text],
            model=self.model_name,
            truncate="END"
        )
        return response.embeddings[0]
    
    def generate_embeddings(self, texts: List[str]) -> List[List[float]]:
        """
        Generate embeddings for a list of texts.
        
        Args:
            texts: List of input texts
            
        Returns:
            List of embedding vectors
        """
        response = self.client.embed(
            texts=texts,
            model=self.model_name,
            truncate="END"
        )
        return [embedding for embedding in response.embeddings]


class SentenceTransformerEmbeddingGenerator:
    """
    Specialized class for generating embeddings using Sentence Transformers.
    """
    
    def __init__(self, model_name: str = "all-MiniLM-L6-v2"):
        """
        Initialize with SentenceTransformer model.
        
        Args:
            model_name: Name of the SentenceTransformer model
        """
        self.model = SentenceTransformer(model_name)
        self.model_name = model_name
    
    def generate_embedding(self, text: str) -> List[float]:
        """
        Generate embedding for a single text.
        
        Args:
            text: Input text
            
        Returns:
            Embedding vector as a list of floats
        """
        embedding = self.model.encode([text])[0]
        return embedding.tolist()
    
    def generate_embeddings(self, texts: List[str]) -> List[List[float]]:
        """
        Generate embeddings for a list of texts.
        
        Args:
            texts: List of input texts
            
        Returns:
            List of embedding vectors
        """
        embeddings = self.model.encode(texts)
        return [embedding.tolist() for embedding in embeddings]
    
    def get_embedding_dimension(self) -> int:
        """
        Get the dimension of the embeddings.
        
        Returns:
            Dimension of the embeddings
        """
        test_embedding = self.generate_embedding("Test text")
        return len(test_embedding)


# Example usage
if __name__ == "__main__":
    # Initialize the embedding generator
    # Using Cohere if API key is available, otherwise using SentenceTransformers
    cohere_key = os.getenv("COHERE_API_KEY")
    
    if cohere_key:
        embed_gen = EmbeddingGenerator(api_key=cohere_key)
        print("Using Cohere for embeddings")
    else:
        embed_gen = EmbeddingGenerator(model_name="all-MiniLM-L6-v2")
        print("Using SentenceTransformers for embeddings")
    
    # Test embedding generation
    test_texts = [
        "This is the first sentence.",
        "This is the second sentence with different content.",
        "Artificial intelligence and machine learning are fascinating fields."
    ]
    
    embeddings = embed_gen.generate_embeddings(test_texts)
    
    print(f"Generated {len(embeddings)} embeddings")
    print(f"Each embedding has dimension: {len(embeddings[0])}")
    print(f"Sample embedding (first 10 values): {embeddings[0][:10]}")